In [2]:
import numpy as np

# The Basics 

In [13]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [14]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [15]:
# Get Dimensions
a.ndim

1

In [16]:
# Get SHape 
b.shape

(2, 3)

In [17]:
# Get Tyep 
a.dtype

dtype('int32')

In [18]:
# Get Size
a.itemsize

4

In [20]:
# Get total size 
a.nbytes 

12

# Accessing?Changing specific elements, rows,columns, etc

In [22]:
a = np. array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r, c]
a[1, 5]

13

In [24]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# Get a specific column 
a[:, 2]

array([ 3, 10])

In [29]:
# Getting a little more fancy[startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [31]:
a[1,5] = 20
print(a)

a[2:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


3-d example 

In [32]:
b = np.array([[[1,2],[3,4],[5,6]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]]]


In [33]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
b[:,1,:1] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Intializing Different Types of Arrays

In [36]:
# ALL 0s matrix 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# ALL 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [38]:
# ANy other number 
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [39]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.74017071, 0.18044961],
       [0.41181445, 0.84028177],
       [0.90779048, 0.87041325],
       [0.41699501, 0.19628987]])

In [45]:
# Random Integer values 
np.random.randint(-4,8, size=(3,3))

array([[ 6,  3,  4],
       [-1,  0, -2],
       [-2,  2,  7]])

In [46]:
# The identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
# Repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be carefull when copying arrays !!!

In [50]:
a = np.array([1,2,3])
b = a.copy()
b = a
b[0] = 100

print(a)

[100   2   3]


# Mathematics 

In [51]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [57]:
a + 2
a

array([3, 4, 5, 6])

In [53]:
a - 2

array([-1,  0,  1,  2])

In [54]:
a * 2

array([2, 4, 6, 8])

In [55]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [59]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [ ]:
a ** 2

In [61]:
# Take the sin 
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Liner Algebra

In [64]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [65]:
# Fibd the determiant
c = np.identity(3)
np.linalg.det(c)

1.0

In [66]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [67]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats, axis=1)

array([3, 6])

In [70]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorgizing Arrays

In [71]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [72]:
# Vertical stackinh vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
# Horizontal stack 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneuos

Load Data from file 

In [81]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# Boolen Masking and Advanced Index 

In [83]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [86]:
# You can index with a list in NumPY 
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [89]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [91]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [92]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])